### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Fangyzh** [gagandeepthapar/satelliteRendezvousSimulation#1]
thanks for your kindness.i got some questions when i ran your code.There are couples of functions, you didn't upload on github,what should one's do to run your code successfully.

**Comment by gagandeepthapar** [comment]
Hello @Fangyzh, unfortunately I don't own some of the functions used in the Transfers. I uploaded some of the functions I do own, however. I recommend looking at "Orbital Mechanics for Engineering Students" (Curtis, 4th edition) for additional resources and code. The chapters and appendices for Relative Motion are what you're looking for.

**Comment by Fangyzh** [comment]
Thanks pal. That's a lot of help. Wish you a good day.











方煜周
中山大学


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Feb 8, 2023 11:47 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [gagandeepthapar/satelliteRendezvousSimulation] questions (Issue #1)

&nbsp;



 
Hello @Fangyzh, unfortunately I don't own some of the functions used in the Transfers. I uploaded some of the functions I do own, however. I recommend looking at "Orbital Mechanics for Engineering Students" (Curtis, 4th edition) for additional resources and code. The chapters and appendices for Relative Motion are what you're looking for.
